### ISSUE TITLE
This method or property is not supported after HttpRequest.GetBufferlessInputStream has been invoked.

### ISSUE THREAD

**Issue by jkatsiotis** [mroach/RollbarSharp#13]
This error occurs when trying to log an exception that took place inside a WCF Rest Service.

Excerpt from Stacktrace: 
   at System.Web.HttpRequest.EnsureFiles()
   at System.Web.HttpRequest.get_Files()
   at RollbarSharp.Builders.RequestModelBuilder.CreateFromHttpRequest(HttpRequest request, HttpSessionState session, String[] scrubParams)
   at RollbarSharp.Builders.RequestModelBuilder.CreateFromCurrentRequest(String[] scrubParams)
   at RollbarSharp.Builders.DataModelBuilder.Create(String level, BodyModel body)
   at RollbarSharp.Builders.DataModelBuilder.CreateExceptionNotice(Exception ex, String message, String level)
   at RollbarSharp.RollbarClient.SendException(Exception ex, String title, String level, Action`1 modelAction)
   at RollbarSharp.RollbarClient.SendErrorException(Exception ex, String title, Action`1 modelAction)

**Comment by hab** [comment]
I got hit by this in my WCF service. I am running .NET 4.5.1. 

Any idea how to prevent RequestModel to stop checking for Files during WCF calls?

**Comment by mzochowski** [comment]
We are using RollbarSharp at https://github.com/jmblab together with Open RIA Services which uses WCF under the hood. We encountered the same issue so we fixed it with following pull request: https://github.com/mroach/RollbarSharp/issues/42

We decided that information about posted files is not crucial so it is better to log without it than not logging at all.

**Comment by mzochowski** [comment]
@hab, @djsolid could you confirm that issue is fixed in your cases?

**Comment by hab** [comment]
I upgraded the solution to use .NET 4.5 instead and wrapped the call to request.Files in a conditional checking if was ok like this: 
```
if (request.ReadEntityBodyMode != ReadEntityBodyMode.Bufferless) {
  ...
}
´´´
It didn't work in .NET 4.0 so I guess that just ignoring the exception is a viable solution.
